name: Publish Open Textbook

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
    paths-ignore:
      - 'original/**'
      - 'README.md'

jobs:
  publish_textbook:
    runs-on: ubuntu-20.04
    steps:
      
      - name: Download Source Files
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: brew install pandoc pandoc-crossref

      - name: Setup PagedJS-CLI
        run: npm install -g pagedjs-cli pagedjs 

      - name: Build Website
        run: |
          bash lantern.sh
          touch ./public/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
